delete from usuario_entity;






INSERT INTO USUARIO_ENTITY (CODIGO_POSTAL, LATITUD, LONGITUD, ID, DTYPE, CONTRASENA, CORREO, ENLACE_REUNION, EXPERIENCIA, FORMACION, FOTO_URL, NOMBRE, PRECIO_HORA, TELEFONO, TIPO, VIDEO_URL) VALUES (110111, 4.60971, -74.08175, 1, 'EstudianteEntity', 'pass1234', 'maria.gomez@example.com', 'https://meet.google.com/maria', 'Participación en semillero de investigación', 'Ingeniería de Sistemas', 'http://dummyimage.com/200x200.png/5fa2dd/ffffff', 'Maria Gomez', '0', '3001234567', 'ESTUDIANTE', 'https://youtube.com/maria/proyecto');
INSERT INTO USUARIO_ENTITY (CODIGO_POSTAL, LATITUD, LONGITUD, ID, DTYPE, CONTRASENA, CORREO, ENLACE_REUNION, EXPERIENCIA, FORMACION, FOTO_URL, NOMBRE, PRECIO_HORA, TELEFONO, TIPO, VIDEO_URL) VALUES (760001, 3.45164, -76.53198, 2, 'EstudianteEntity', 'securePass!', 'juan.perez@example.com', 'https://zoom.us/juan', 'Pasantía en multinacional', 'Administración de Empresas', 'http://dummyimage.com/200x200.png/dddddd/000000', 'Juan Perez', '0', '3109876543', 'ESTUDIANTE', 'https://vimeo.com/juan/charla');
INSERT INTO USUARIO_ENTITY (CODIGO_POSTAL, LATITUD, LONGITUD, ID, DTYPE, CONTRASENA, CORREO, ENLACE_REUNION, EXPERIENCIA, FORMACION, FOTO_URL, NOMBRE, PRECIO_HORA, TELEFONO, TIPO, VIDEO_URL) VALUES (500001, 7.12345, -73.13496, 3, 'EstudianteEntity', 'qwerty789', 'laura.martinez@example.com', 'https://teams.microsoft.com/laura', 'Proyecto social universitario', 'Psicología', 'http://dummyimage.com/200x200.png/ff4444/ffffff', 'Laura Martinez', '0', '3201122334', 'ESTUDIANTE', 'https://youtube.com/laura/psicologia');
INSERT INTO USUARIO_ENTITY (CODIGO_POSTAL, LATITUD, LONGITUD, ID, DTYPE, CONTRASENA, CORREO, ENLACE_REUNION, EXPERIENCIA, FORMACION, FOTO_URL, NOMBRE, PRECIO_HORA, TELEFONO, TIPO, VIDEO_URL) VALUES (050001, 6.2442, -75.5812, 4, 'EstudianteEntity', 'admin2024', 'carlos.lopez@example.com', 'https://zoom.us/carlos', 'Voluntariado en alfabetización digital', 'Comunicación Social', 'http://dummyimage.com/200x200.png/000000/ffffff', 'Carlos Lopez', '0', '3015566778', 'ESTUDIANTE', 'https://vimeo.com/carlos/comunicacion');
INSERT INTO USUARIO_ENTITY (CODIGO_POSTAL, LATITUD, LONGITUD, ID, DTYPE, CONTRASENA, CORREO, ENLACE_REUNION, EXPERIENCIA, FORMACION, FOTO_URL, NOMBRE, PRECIO_HORA, TELEFONO, TIPO, VIDEO_URL) VALUES (190001, 2.44108, -76.6069, 5, 'EstudianteEntity', 'mypassword', 'paula.sanchez@example.com', 'https://meet.google.com/paula', 'Participante de Olimpiadas de Matemáticas', 'Matemáticas', 'http://dummyimage.com/200x200.png/ffcc00/000000', 'Paula Sanchez', '0', '3156789012', 'ESTUDIANTE', 'https://youtube.com/paula/olimpiadas');
INSERT INTO USUARIO_ENTITY (CODIGO_POSTAL, LATITUD, LONGITUD, ID, DTYPE, CONTRASENA, CORREO, ENLACE_REUNION, EXPERIENCIA, FORMACION, FOTO_URL, NOMBRE, PRECIO_HORA, TELEFONO, TIPO, VIDEO_URL) VALUES (150001, 5.53528, -73.36778, 6, 'EstudianteEntity', 'letmein123', 'luis.fernandez@example.com', 'https://meet.jit.si/luis', 'Monitor académico en Física', 'Física', 'http://dummyimage.com/200x200.png/cc0000/ffffff', 'Luis Fernandez', '0', '3009988776', 'ESTUDIANTE', 'https://vimeo.com/luis/fisica');
INSERT INTO USUARIO_ENTITY (CODIGO_POSTAL, LATITUD, LONGITUD, ID, DTYPE, CONTRASENA, CORREO, ENLACE_REUNION, EXPERIENCIA, FORMACION, FOTO_URL, NOMBRE, PRECIO_HORA, TELEFONO, TIPO, VIDEO_URL) VALUES (200001, 8.76417, -75.87958, 7, 'EstudianteEntity', 'changeme', 'ana.garcia@example.com', 'https://zoom.us/ana', 'Investigadora junior en biología', 'Biología', 'http://dummyimage.com/200x200.png/5fa2dd/000000', 'Ana Garcia', '0', '3023344556', 'ESTUDIANTE', 'https://youtube.com/ana/biologia');
INSERT INTO USUARIO_ENTITY (CODIGO_POSTAL, LATITUD, LONGITUD, ID, DTYPE, CONTRASENA, CORREO, ENLACE_REUNION, EXPERIENCIA, FORMACION, FOTO_URL, NOMBRE, PRECIO_HORA, TELEFONO, TIPO, VIDEO_URL) VALUES (730001, 4.43889, -75.23222, 8, 'EstudianteEntity', 'testuser1', 'david.moreno@example.com', 'https://meet.google.com/david', 'Auxiliar de laboratorio de química', 'Química', 'http://dummyimage.com/200x200.png/0099cc/ffffff', 'David Moreno', '0', '3104455667', 'ESTUDIANTE', 'https://vimeo.com/david/quimica');
INSERT INTO USUARIO_ENTITY (CODIGO_POSTAL, LATITUD, LONGITUD, ID, DTYPE, CONTRASENA, CORREO, ENLACE_REUNION, EXPERIENCIA, FORMACION, FOTO_URL, NOMBRE, PRECIO_HORA, TELEFONO, TIPO, VIDEO_URL) VALUES (470001, 11.24079, -74.19904, 9, 'EstudianteEntity', 'demo123', 'andrea.castillo@example.com', 'https://teams.microsoft.com/andrea', 'Colaboración en revista estudiantil', 'Literatura', 'http://dummyimage.com/200x200.png/ff4444/000000', 'Andrea Castillo', '0', '3206677889', 'ESTUDIANTE', 'https://youtube.com/andrea/literatura');
INSERT INTO USUARIO_ENTITY (CODIGO_POSTAL, LATITUD, LONGITUD, ID, DTYPE, CONTRASENA, CORREO, ENLACE_REUNION, EXPERIENCIA, FORMACION, FOTO_URL, NOMBRE, PRECIO_HORA, TELEFONO, TIPO, VIDEO_URL) VALUES (680001, 7.12539, -73.1198, 10, 'EstudianteEntity', 'springboot', 'julian.mendez@example.com', 'https://zoom.us/julian', 'Participante en hackathons de programación', 'Ingeniería de Software', 'http://dummyimage.com/200x200.png/ffffff/000000', 'Julian Mendez', '0', '3005544332', 'ESTUDIANTE', 'https://vimeo.com/julian/codigo');
